- name: Playbook fuer Gruppe prod_azure_linux
  hosts: prod_azure_linux
  #environment: "{{proxy_env}}"
  become: yes
  become_method: sudo
  tasks:
  - name: set timezone to Europe/Berlin
    timezone:
      name: Europe/Berlin

#################### HOSTS #####################

- name: Playbook fuer webserver-demo
  hosts: webserver-demo
  #environment: "{{proxy_env}}"
  become: yes
  become_method: sudo
  tasks:
    - name: install software
      apt:
        name: 
          - apache2
        state: present
    - name: enable apache modules
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - headers
        - rewrite
        - ssl
        - proxy
        - proxy_http
        - proxy_ajp
      notify:
        - restart apache2
  handlers:
    - name: restart apache2
      service: 
        name: apache2 
        state: restarted